# Generated by Django 4.1.3 on 2022-12-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('programmer', models.CharField(max_length=75)),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='Projects images')),
                ('file', models.FileField(upload_to='Projects files')),
            ],
        ),
    ]
